### ISSUE TITLE
add extra launch button

### ISSUE THREAD

**Issue by freeman-lab** [binder-project/binder-web#4]
As suggested by @drphilmarshall, the space currently occupied by "BUILD STATUS" on the right could maybe be better served with an extra, larger launch button, with a color depending on the build state.

![screen shot 2016-06-14 at 5 17 24 pm](https://cloud.githubusercontent.com/assets/3387500/16064210/e93d2744-3253-11e6-8093-cda4ac6bec9b.png)

**Comment by freeman-lab** [comment]
Mock ups for the UI are welcome!

**Comment by freeman-lab** [comment]
Here's a mock up that addresses this issue as well as #3 

![screen shot 2016-07-07 at 1 07 24 pm](https://cloud.githubusercontent.com/assets/3387500/16662080/d3bafbba-4443-11e6-9255-6ecefa8e8973.png)

**Comment by drphilmarshall** [comment]
That looks nice :-) I'd vote for removing the launch button inside the
central box if you go with the big button outside the box. That way, all
the building and rebuilding would happen inside the central box, and
launching would be kept separate - which I think works better, conceptually.

**Comment by freeman-lab** [comment]
Hehe since you commented we had another proposal from @andrewosh , which just drops the extra button entirely. This now might be my favorite 😄 

![screen shot 2016-07-07 at 1 44 38 pm](https://cloud.githubusercontent.com/assets/3387500/16663175/4176b874-4449-11e6-8dc2-087031689558.png)

**Comment by drphilmarshall** [comment]
That's nice too, and looks easy to implement :-)

**Comment by freeman-lab** [comment]
Cool thanks @drphilmarshall updates version is now live on the beta server, you can see it here http://beta.mybinder.org/status/binder-project/example-requirements

**Comment by drphilmarshall** [comment]
Very good! :-)

**Comment by drphilmarshall** [comment]
Yes! Saw this on the new site, it's great. Nice work, all - and thank you
very much! :-)

**Comment by freeman-lab** [comment]
Cool, thanks for all the feedback @drphilmarshall !
